//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLabWPF.Infrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employees1 = new HashSet<Employee>();
            this.Orders = new HashSet<Order>();
            this.Territories = new HashSet<Territory>();
        }
    
        [DataMember]
		public int EmployeeID { get; set; }
        [DataMember]
		public string LastName { get; set; }
        [DataMember]
		public string FirstName { get; set; }
        [DataMember]
		public string Title { get; set; }
        [DataMember]
		public string TitleOfCourtesy { get; set; }
        [DataMember]
		public Nullable<System.DateTime> BirthDate { get; set; }
        [DataMember]
		public Nullable<System.DateTime> HireDate { get; set; }
        [DataMember]
		public string Address { get; set; }
        [DataMember]
		public string City { get; set; }
        [DataMember]
		public string Region { get; set; }
        [DataMember]
		public string PostalCode { get; set; }
        [DataMember]
		public string Country { get; set; }
        [DataMember]
		public string HomePhone { get; set; }
        [DataMember]
		public string Extension { get; set; }
        [DataMember]
		public byte[] Photo { get; set; }
        [DataMember]
		public string Notes { get; set; }
        [DataMember]
		public Nullable<int> ReportsTo { get; set; }
        [DataMember]
		public string PhotoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
		public virtual ICollection<Employee> Employees1 { get; set; }
        [DataMember]
		public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
		public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
		public virtual ICollection<Territory> Territories { get; set; }
    }
}
