//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLabWPF.Infrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }
    
        [DataMember]
		public int OrderID { get; set; }
        [DataMember]
		public string CustomerID { get; set; }
        [DataMember]
		public Nullable<int> EmployeeID { get; set; }
        [DataMember]
		public Nullable<System.DateTime> OrderDate { get; set; }
        [DataMember]
		public Nullable<System.DateTime> RequiredDate { get; set; }
        [DataMember]
		public Nullable<System.DateTime> ShippedDate { get; set; }
        [DataMember]
		public Nullable<int> ShipVia { get; set; }
        [DataMember]
		public Nullable<decimal> Freight { get; set; }
        [DataMember]
		public string ShipName { get; set; }
        [DataMember]
		public string ShipAddress { get; set; }
        [DataMember]
		public string ShipCity { get; set; }
        [DataMember]
		public string ShipRegion { get; set; }
        [DataMember]
		public string ShipPostalCode { get; set; }
        [DataMember]
		public string ShipCountry { get; set; }
    
        [DataMember]
		public virtual Customer Customer { get; set; }
        [DataMember]
		public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
		public virtual ICollection<Order_Detail> Order_Details { get; set; }
        [DataMember]
		public virtual Shipper Shipper { get; set; }
    }
}
