//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLabWPF.Infrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }
    
        [DataMember]
		public int ProductID { get; set; }
        [DataMember]
		public string ProductName { get; set; }
        [DataMember]
		public Nullable<int> SupplierID { get; set; }
        [DataMember]
		public Nullable<int> CategoryID { get; set; }
        [DataMember]
		public string QuantityPerUnit { get; set; }
        [DataMember]
		public Nullable<decimal> UnitPrice { get; set; }
        [DataMember]
		public Nullable<short> UnitsInStock { get; set; }
        [DataMember]
		public Nullable<short> UnitsOnOrder { get; set; }
        [DataMember]
		public Nullable<short> ReorderLevel { get; set; }
        [DataMember]
		public bool Discontinued { get; set; }
    
        [DataMember]
		public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
		public virtual ICollection<Order_Detail> Order_Details { get; set; }
        [DataMember]
		public virtual Supplier Supplier { get; set; }
    }
}
